# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'yerkontrolisen.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QTimer
from dronekit import connect, VehicleMode,LocationGlobalRelative
import time





connection_string="127.0.0.1:14550"
iha = connect(connection_string, wait_ready=True)

class Ui_MainWindow(object):
    def __init__(self):
        super().__init__()
        self.iha = None

        self.timer = QTimer()
        self.timer.timeout.connect(self.update_labels)
        self.timer.start(2000)

    def update_labels(self):
        if self.iha != iha:
            return

        try:

            yukseklik = self.iha.location.global_relative_frame.alt
            hava_hizi = self.iha.groundspeed
            gps_hizi = self.iha.gps_hizi
            batarya = self.iha.batarya.level
            mod_durum = self.iha.mod_durum.name
            gps_sayisi = self.iha.gps_0.satellites_visible
            pass
        except Exception as e:
            print(f"Hata: {e}")


            self.yukseklik.setText(f"Yükseklik: {yukseklik:.2f} m")
            self.hava_hizi.setText(f"Hava Hızı: {hava_hizi:.2f} m/s")
            self.gps_hizi.setText(f"GPS Hızı: {gps_hizi:.2f} m/s")
            self.batarya.setText(f"Batarya: %{batarya}")
            self.mod_durumu.setText(f"Uçuş modu: {mod_durumu}")
            self.gps_sayisi.setText(f"Gps Uydu Sayısı: {gps_sayisi}")



    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(923, 833)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.output_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.output_lineEdit.setGeometry(110, 500, 300, 30)
        self.output_lineEdit.setStyleSheet("background-color: rgb(64, 67, 191);\n"
                                        "")
        self.output_lineEdit.setReadOnly(True)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 10, 851, 771))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.takeoff_tusu = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.takeoff_tusu.setStyleSheet("background-color: rgb(64, 67, 191);\n"
"")
        self.takeoff_tusu.setAutoRepeatInterval(100)
        self.takeoff_tusu.setObjectName("takeoff_tusu")
        self.gridLayout.addWidget(self.takeoff_tusu, 11, 2, 1, 1)
        self.takeoff_tusu.clicked.connect(self.takeoff)
        self.baud = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.baud.setStyleSheet("background-color: rgb(38, 162, 105);\n"
"color: rgb(0, 0, 0);")
        self.baud.setObjectName("baud")
        self.gridLayout.addWidget(self.baud, 13, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 8, 1, 1, 1)
        self.arm_tusu = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.arm_tusu.setStyleSheet("\n"
"background-color: rgb(243, 137, 229);")
        self.arm_tusu.setObjectName("arm_tusu")
        self.gridLayout.addWidget(self.arm_tusu, 6, 2, 1, 1)
        self.arm_tusu.clicked.connect(self.arm_ol)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 0, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 8, 5, 1, 1)
        self.stabilize_tusu = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.stabilize_tusu.setStyleSheet("background-color: rgb(243, 137, 229);")
        self.stabilize_tusu.setObjectName("stabilize_tusu")
        self.gridLayout.addWidget(self.stabilize_tusu, 8, 4, 1, 1)
        self.stabilize_tusu.clicked.connect(self.stabilize)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.gps_sayisi = QtWidgets.QLabel(self.centralwidget)
        self.gps_sayisi.setStyleSheet("background-color: rgb(38, 162, 105);\n"
"color: rgb(23, 2, 65);")
        self.gps_sayisi.setObjectName("gps_sayisi_count_label")
        self.verticalLayout_8.addWidget(self.gps_sayisi)

        self.telemetri = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.telemetri.setStyleSheet("background-color: rgb(38, 162, 105);color: rgb(23, 2, 65);\n"
"")
        self.telemetri.setObjectName("telemetri")
        self.verticalLayout_8.addWidget(self.telemetri)
        self.batarya = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.batarya.setStyleSheet("background-color: rgb(38, 162, 105);color: rgb(23, 2, 65);")
        self.batarya.setObjectName("batarya")
        self.verticalLayout_8.addWidget(self.batarya)
        self.ucus_suresi = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.ucus_suresi.setStyleSheet("background-color: rgb(38, 162, 105);color: rgb(23, 2, 65);")
        self.ucus_suresi.setObjectName("ucus_suresi")
        self.verticalLayout_8.addWidget(self.ucus_suresi)
        self.arm = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.arm.setStyleSheet("background-color: rgb(38, 162, 105);color: rgb(23, 2, 65);")
        self.arm.setObjectName("arm")
        self.verticalLayout_8.addWidget(self.arm)
        self.mod_durumu = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.mod_durumu.setStyleSheet("background-color: rgb(38, 162, 105);color: rgb(23, 2, 65);")
        self.mod_durumu.setObjectName("mod_durumu")
        self.verticalLayout_8.addWidget(self.mod_durumu)
        self.verticalLayout_2.addLayout(self.verticalLayout_8)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 5, 1, 1)
        self.disarm_tusu = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.disarm_tusu.setStyleSheet("background-color: rgb(243, 137, 229);")
        self.disarm_tusu.setObjectName("disarm_tusu")
        self.gridLayout.addWidget(self.disarm_tusu, 6, 3, 1, 1)
        self.disarm_tusu.clicked.connect(self.disarm_ol)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 15, 4, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout.addLayout(self.horizontalLayout, 15, 5, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout.addLayout(self.verticalLayout_3, 1, 4, 1, 1)
        self.gorev_tusu = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.gorev_tusu.setStyleSheet("\n"
"background-color: rgb(64, 67, 191);")
        self.gorev_tusu.setObjectName("gorev_tusu")
        self.gridLayout.addWidget(self.gorev_tusu, 11, 4, 1, 1)
        self.loiter_tusu = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.loiter_tusu.setStyleSheet("background-color: rgb(243, 137, 229);")
        self.loiter_tusu.setObjectName("loiter_tusu")
        self.gridLayout.addWidget(self.loiter_tusu, 8, 2, 1, 1)
        self.loiter_tusu.clicked.connect(self.loiter)
        self.land_tusu = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.land_tusu.setStyleSheet("background-color: rgb(243, 137, 229);")
        self.land_tusu.setObjectName("land_tusu")
        self.gridLayout.addWidget(self.land_tusu, 11, 3, 1, 1)
        self.land_tusu.clicked.connect(self.land)
        self.guided_tusu = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.guided_tusu.setStyleSheet("background-color: rgb(243, 137, 229);")
        self.guided_tusu.setObjectName("guided_tusu")
        self.gridLayout.addWidget(self.guided_tusu, 8, 3, 1, 1)
        self.guided_tusu.clicked.connect(self.guided_modu_ayarla)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 2, 1, 1)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.yukseklik = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.yukseklik.setStyleSheet("background-color: rgb(38, 162, 105);\n"
"color: rgb(23, 2, 65);")
        self.yukseklik.setObjectName("yukseklik")
        self.verticalLayout_7.addWidget(self.yukseklik)
        self.hava_hizi = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.hava_hizi.setStyleSheet("background-color: rgb(38, 162, 105);\n"
"color: rgb(23, 2, 65);")
        self.hava_hizi.setObjectName("hava_hizi")
        self.verticalLayout_7.addWidget(self.hava_hizi)
        self.gps_hizi = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.gps_hizi.setStyleSheet("background-color: rgb(38, 162, 105);\n"
"color: rgb(23, 2, 65);")
        self.gps_hizi.setObjectName("gps_hizi")
        self.verticalLayout_7.addWidget(self.gps_hizi)
        self.uzaklik = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.uzaklik.setStyleSheet("background-color: rgb(38, 162, 105);color: rgb(23, 2, 65);")
        self.uzaklik.setObjectName("uzaklik")
        self.verticalLayout_7.addWidget(self.uzaklik)
        self.pitch = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.pitch.setStyleSheet("color: rgb(23, 2, 65);\n"
"background-color: rgb(38, 162, 105);")
        self.pitch.setObjectName("pitch")
        self.verticalLayout_7.addWidget(self.pitch)
        self.roll = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.roll.setStyleSheet("color: rgb(23, 2, 65);\n"
"background-color: rgb(38, 162, 105);")
        self.roll.setObjectName("roll")
        self.verticalLayout_7.addWidget(self.roll)
        self.yaw = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.yaw.setStyleSheet("background-color: rgb(38, 162, 105);\n"
"color: rgb(23, 2, 65);")
        self.yaw.setObjectName("yaw")
        self.verticalLayout_7.addWidget(self.yaw)
        self.gridLayout.addLayout(self.verticalLayout_7, 0, 1, 1, 1)
        self.ip = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.ip.setStyleSheet("background-color: rgb(38, 162, 105);\n"
"color: rgb(0, 0, 0);")
        self.ip.setObjectName("ip")
        self.gridLayout.addWidget(self.ip, 12, 1, 1, 1)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.gridLayout.addLayout(self.verticalLayout_9, 0, 3, 1, 1)
        self.rtl_tusu = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.rtl_tusu.setStyleSheet("background-color: rgb(243, 137, 229);")
        self.rtl_tusu.setObjectName("rtl_tusu")
        self.gridLayout.addWidget(self.rtl_tusu, 6, 4, 1, 1)
        self.rtl_tusu.clicked.connect(self.rtl)
        self.tarih = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.tarih.setStyleSheet("background-color: rgb(38, 162, 105);\n"
"color: rgb(0, 0, 0);")
        self.tarih.setObjectName("tarih")
        self.gridLayout.addWidget(self.tarih, 12, 5, 1, 1)
        self.saat = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.saat.setStyleSheet("background-color: rgb(38, 162, 105);\n"
"color: rgb(0, 0, 0);")
        self.saat.setObjectName("saat")
        self.gridLayout.addWidget(self.saat, 13, 5, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 923, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)




    def update_output(self, message):
        self.output_lineEdit.setText(message)

    def guided_modu_ayarla(self):
        iha.mode = VehicleMode("GUIDED")
        time.sleep(1)
        if iha.mode.name == "GUIDED":
            self.update_output("guided moduna geçildi")
        else:
            self.update_output("guided moduna geçiş başarısız")

    def arm_ol(self):

        iha.arm()
        self.update_output("iha arm edildi")

    def takeoff(self):
        iha.simple_takeoff(10)
        self.update_output("takeoff başlatıldı")
        while True:
            mevcut_irtifa = iha.location.global_relative_frame.alt
            if mevcut_irtifa >= 10 * 0.95:
                self.update_output("istenilen irtifaya ulaşıldı")
                break
            time.sleep(1)

    def land(self):
        iha.mode = VehicleMode("LAND")

        if iha.location.global_relative_frame.alt == 0:
            self.update_output("iniş gerçekleşti")

    def stabilize(self):
        iha.mode = VehicleMode("STABILIZE")
        self.update_output("stabilize moda geçiş yapılıyor")

    def loiter(self):
        iha.mode = VehicleMode("LOITER")

    def rtl(self):
        iha.mode = VehicleMode("RTL")

    def disarm_ol(self):
        if iha.location.global_relative_frame.alt >= 3:
            self.update_output("irtifa üç metrenin üstüne çıkarsa disarm edilemez")
            return

        iha.armed = False
        self.update_output("disarm başarılı")







        return iha

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.takeoff_tusu.setText(_translate("MainWindow", "TAKEOFF"))
        self.baud.setText(_translate("MainWindow", "BAUD:"))
        self.arm_tusu.setText(_translate("MainWindow", "ARM"))
        self.stabilize_tusu.setText(_translate("MainWindow", "STABILIZE"))
        self.gps_sayisi.setText(_translate("MainWindow", "GPS SAYISI:"))
        self.telemetri.setText(_translate("MainWindow", "TELEMETRİ:"))
        self.batarya.setText(_translate("MainWindow", "BATARYA:"))
        self.ucus_suresi.setText(_translate("MainWindow", "UÇUŞ SÜRESİ:"))
        self.arm.setText(_translate("MainWindow", "ARM:"))
        self.mod_durumu.setText(_translate("MainWindow", "MOD DURUM:"))
        self.disarm_tusu.setText(_translate("MainWindow", "DISARM"))
        self.gorev_tusu.setText(_translate("MainWindow", "GOREV"))
        self.loiter_tusu.setText(_translate("MainWindow", "LOITER"))
        self.land_tusu.setText(_translate("MainWindow", "LAND"))
        self.guided_tusu.setText(_translate("MainWindow", "GUIDED"))
        self.yukseklik.setText(_translate("MainWindow", "YÜKSEKLİK:"))
        self.hava_hizi.setText(_translate("MainWindow", "HAVA HIZI:"))
        self.gps_hizi.setText(_translate("MainWindow", "GPS HIZI:"))
        self.uzaklik.setText(_translate("MainWindow", "UZAKLIK:"))
        self.pitch.setText(_translate("MainWindow", "PITCH:"))
        self.roll.setText(_translate("MainWindow", "ROLL:"))
        self.yaw.setText(_translate("MainWindow", "YAW:"))
        self.ip.setText(_translate("MainWindow", "IP:"))
        self.rtl_tusu.setText(_translate("MainWindow", "RTL"))
        self.tarih.setText(_translate("MainWindow", "TARİH:"))
        self.saat.setText(_translate("MainWindow", "SAAT:"))

    def test_output(self):
        message = "Drone initialized."
        self.output_lineEdit.setText(message)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
